---
- name: Install Applications
  hosts: all
  tasks:
          - name: Create service user
            win_user:
                    name: svc_marte_user
                    password: svc_p@ssw0rd
                    state: present
                    groups:
                            - Users
                            - Administrators

